#!/usr/bin/env python3
"""Generate shntool mode/format module glue source.

Usage: gen_glue.py TYPE OUTPUT MODULE...
"""

import sys


def generate(kind: str, modules: list[str]) -> str:
    lines = [
        "/* Generated by utils/gen_glue.py. Do not edit by hand. */",
        "",
        '#include "shntool.h"',
        "",
    ]
    for module in modules:
        lines.append(f"extern {kind}_module {kind}_{module};")
    lines.append("")
    lines.append(f"{kind}_module *st_{kind}s[] = {{")
    for module in modules:
        lines.append(f"  &{kind}_{module},")
    lines.append("  NULL")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2

    kind, output, *modules = argv[1:]
    with open(output, "w", encoding="utf-8") as handle:
        handle.write(generate(kind, modules))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
